version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: solo-app-empresariales
    restart: always
    ports:
      - "3005:3005"
    environment:
      - NODE_ENV=production
      - PORT=3005
    # Añade volúmenes si necesitas persistencia de datos
    # volumes:
    #   - ./data:/app/data